export const mockSearch = [
  {
    id: 972437,
    name: 'Playground (from the series Arcane League of Legends)',
    trackName: 'Playground (from the series Arcane League of Legends)',
    artistName: 'Bea Miller',
    albumName: 'Arcane League of Legends (Soundtrack from the Animated Series)',
    duration: 231,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 984491,
    name: 'FEEL SOMETHING DIFFERENT',
    trackName: 'FEEL SOMETHING DIFFERENT',
    artistName: 'Bea Miller feat. Aminé',
    albumName: 'FEEL SOMETHING DIFFERENT',
    duration: 207,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1010348,
    name: 'THE BADDEST',
    trackName: 'THE BADDEST',
    artistName: 'K/DA feat. (G)I-DLE, Wolftyla, Bea Miller & League of Legends',
    albumName: 'THE BADDEST',
    duration: 163,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1040655,
    name: 'I Wanna Know (feat. Bea Miller)',
    trackName: 'I Wanna Know (feat. Bea Miller)',
    artistName: 'NOTD feat. Bea Miller',
    albumName: 'I Wanna Know (feat. Bea Miller)',
    duration: 198,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1040656,
    name: 'I Wanna Know (Feat. Bea Miller)',
    trackName: 'I Wanna Know (Feat. Bea Miller)',
    artistName: 'Notd',
    albumName: 'I Wanna Know (Feat. Bea Miller) - Single',
    duration: 198,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081378,
    name: 'FEEL SOMETHING DIFFERENT',
    trackName: 'FEEL SOMETHING DIFFERENT',
    artistName: 'Bea Miller',
    albumName: 'elated!',
    duration: 207,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081379,
    name: 'forever is a lie',
    trackName: 'forever is a lie',
    artistName: 'Bea Miller',
    albumName: 'elated!',
    duration: 152,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081380,
    name: 'hallelujah',
    trackName: 'hallelujah',
    artistName: 'Bea Miller',
    albumName: 'elated!',
    duration: 172,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081381,
    name: 'i never wanna die',
    trackName: 'i never wanna die',
    artistName: 'Bea Miller',
    albumName: 'elated!',
    duration: 175,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081382,
    name: 'lonely bitch',
    trackName: 'lonely bitch',
    artistName: 'Bea Miller',
    albumName: 'lonely bitch - Single',
    duration: 176,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081383,
    name: 'lonely bitch',
    trackName: 'lonely bitch',
    artistName: 'Bea Miller',
    albumName: 'lonely bitch',
    duration: 176,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081384,
    name: 'making bad decisions',
    trackName: 'making bad decisions',
    artistName: 'Bea Miller',
    albumName: 'elated!',
    duration: 203,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081388,
    name: 'self crucify',
    trackName: 'self crucify',
    artistName: 'Bea Miller',
    albumName: 'elated!',
    duration: 241,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1081389,
    name: 'wisdom teeth',
    trackName: 'wisdom teeth',
    artistName: 'Bea Miller',
    albumName: 'elated!',
    duration: 181,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1136596,
    name: 'Playground',
    trackName: 'Playground',
    artistName: 'Bea Miller',
    albumName: 'Arcane League of Legends (Soundtrack From the Animated Series)',
    duration: 231,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1151705,
    name: 'Fire N Gold',
    trackName: 'Fire N Gold',
    artistName: 'Bea Miller',
    albumName: 'Not An Apology',
    duration: 212,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1151706,
    name: 'Fire N Gold',
    trackName: 'Fire N Gold',
    artistName: 'Bea Miller',
    albumName: 'Young Blood',
    duration: 212,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1178167,
    name: "We Can't Stop (feat. Bea Miller)",
    trackName: "We Can't Stop (feat. Bea Miller)",
    artistName: 'Boyce Avenue feat. Bea Miller',
    albumName: 'Cover Collaborations, Vol. 2',
    duration: 222,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1802567,
    name: 'Fire n Gold',
    trackName: 'Fire n Gold',
    artistName: 'Bea Miller',
    albumName: 'Mainstream Radio February 2015',
    duration: 212,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  },
  {
    id: 1806770,
    name: 'I Wanna Know',
    trackName: 'I Wanna Know',
    artistName: 'NOTD Ft Bea Miller',
    albumName: 'Mainstream Radio June 2018',
    duration: 198,
    instrumental: false,
    plainLyrics: '...',
    syncedLyrics: '...'
  }
];
